name: trwiki
label: Turkish Wikipedia
host: tr.wikipedia.org

external_samples:
  sampled_revisions.20k_2015:
    quarry_url: http://quarry.wmflabs.org/run/168286/output/0/json-lines?download=true
  sampled_revisions.20k_2020:
    quarry_url: http://quarry.wmflabs.org/run/495204/output/0/json-lines?download=true
  human_labeled_revisions.20k_2015:
    labeling_campaign: https://labels.wmflabs.org/campaigns/trwiki/5/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
    - sysop
    - oversight
    - bot
    - rollbacker
    - checkuser
    - abusefilter
    - bureaucrat
    - flow-bot
    - interface-admin
    - interface-editor
    - patroller
  labeled_samples:
    autolabeled_revisions.20k_2020: sampled_revisions.20k_2020

merged_samples:
  labeled_revisions.20k_2015:
    - human_labeled_revisions.20k_2015

extracted_samples:
  labeled_revisions.w_cache.20k_2015:
    sample: labeled_revisions.20k_2015
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.20k_2015
    label: damaging
    pop_rate_true: 0.0495014425266994
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
  goodfaith:
    observations: labeled_revisions.w_cache.20k_2015
    label: goodfaith
    pop_rate_true: 0.9538897605911829
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
